### PR TITLE
LSPS1: Fix API to maintain consistency

### LINKED ISSUE #92: LSPS1: Fix API to maintain consistency with protocol
Rename functions/documentation with `invoice` to avoid confusion with _lightning-invoice_ and to make it more compliant with the protocol.

### PR DESCRIPTION
**Pull request by Srg213**
Closes #92 and #89.

### CODE REVIEW

File: src/lsps1/client.rs [hunk 1]
```diff
@@ -300,7 +300,7 @@ where
 
 				self.pending_events.enqueue(Event::LSPS1Client(LSPS1ClientEvent::GetInfoResponse {
 					id: channel_id,
-					request_id,
+
```
Comment (tnull) [inline src/lsps1/client.rs]: nit: Delete superfluous whitespace introduced here.

File: src/lsps1/event.rs [hunk 2]
```diff
@@ -76,15 +74,15 @@ pub enum LSPS1ServiceEvent {
...
-	/// generate a complete invoice including the details regarding the
+	/// You must call [`LSPS1ServiceHandler::send_payment_details`] to
+	/// send order parameters including the details regarding the
 	/// payment and order id for this order for the client.
 	///
-	/// [`LSPS1ServiceHandler::send_invoice_for_order`]: crate::lsps1::service::LSPS1ServiceHandler::send_invoice_for_order
-	CreateInvoice {
-		/// An identifier that must be passed to [`LSPS1ServiceHandler::send_invoice_for_order`].
+	/// [`LSPS1ServiceHandler::send_payment_details`]: crate::lsps1::service::LSPS1ServiceHandler::send_payment_details
+	RequestforPaymentDetails {
```
Comment (tnull) [inline src/lsps1/event.rs]: nit: The `f` should probably be captitalized, i.e., `RequestForPaymentDetails`.

**Review by tnull — COMMENTED** [review]
Generally LGTM, mod two nits.

**Review by tnull — APPROVED** [review]
LGTM
